#!/bin/bash


echo -e "ingrese nombre del proyecto:"

read var
npx create-react-app $var


cd $var
yarn add mobx mobx-react
yarn add antd react-app-rewired customize-cra babel-plugin-import
yarn add tachyons

echo "const { override, fixBabelImports } = require('customize-cra');
module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css',
  }),
);" > config-overrides.js


sed -i 's/react-scripts start/react-app-rewired start/g' package.json
sed -i 's/react-scripts build/react-app-rewired build/g' package.json
sed -i 's/react-scripts test/react-app-rewired test/g' package.json


#yarn start







 
